### ISSUE TITLE
Is it possible to create new colors/effects?

### ISSUE THREAD

**Issue by nettoyoussef** [threadexio/Legion-Y720-Keyboard-Backlight#1]
Hi, thanks for your effort in creating this package.

I made it available on the Arch User Repository [here](https://aur.archlinux.org/packages/legion-y720-keyboard-backlight-git/).

As the title implies, is it possible to create new colors or change effects, or are we bound to the current ones?

**Comment by threadexio** [comment]
Thank you for packaging it for the AUR!

As far as I know creating completely new effects would require flashing new firmware on the device that implements those new effects. As for colors you would have to flash new firmware again. Although I'm not sure that would work, because colors might be a hardware limitation of the LEDs themselves.

One possible solution for now would be having profiles to represent each possible LED combination of the effect you are trying to create and switching between them with a simple bash script, in which you could change timings, execute other programs, etc.

**Comment by nettoyoussef** [comment]
Thanks for your fast response!
I was not sure if the colors/effects were being sorted at the program or firmware level, as I did not take the time to really understand the code.

Your answer clarified that to me.
Since the addition of new effects/colors would be more of a hack that is not really intended for the overall program, I will close this issue.
